// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EH9Hlo4QlwBsz5I8FAPYsGjXT9D6jfQ',
    appId: '1:966584511720:web:a6155748386c0152d26d5d',
    messagingSenderId: '966584511720',
    projectId: 'newshut-7e124',
    authDomain: 'newshut-7e124.firebaseapp.com',
    storageBucket: 'newshut-7e124.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuO_Fvg5LmuNm6c80DXYpgwp_bwF5-vqk',
    appId: '1:966584511720:android:f8feb547cba01ecbd26d5d',
    messagingSenderId: '966584511720',
    projectId: 'newshut-7e124',
    storageBucket: 'newshut-7e124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU-iwMTk0yN7KBfga4IX9hAm7tLD4KLCY',
    appId: '1:966584511720:ios:b9d8b9413a603744d26d5d',
    messagingSenderId: '966584511720',
    projectId: 'newshut-7e124',
    storageBucket: 'newshut-7e124.firebasestorage.app',
    iosClientId: '966584511720-7lvqbe5er3ofiqf03n47q9s8etg63m9m.apps.googleusercontent.com',
    iosBundleId: 'com.newshunt.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU-iwMTk0yN7KBfga4IX9hAm7tLD4KLCY',
    appId: '1:966584511720:ios:03548df613a36a06d26d5d',
    messagingSenderId: '966584511720',
    projectId: 'newshut-7e124',
    storageBucket: 'newshut-7e124.firebasestorage.app',
    iosClientId: '966584511720-06tb439so54saejt5llq9di3h8nasae5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2EH9Hlo4QlwBsz5I8FAPYsGjXT9D6jfQ',
    appId: '1:966584511720:web:0a852c9235be6314d26d5d',
    messagingSenderId: '966584511720',
    projectId: 'newshut-7e124',
    authDomain: 'newshut-7e124.firebaseapp.com',
    storageBucket: 'newshut-7e124.firebasestorage.app',
  );
}
